server:
  port: 8081

spring:
  application:
    name: core-api

  datasource:
    url: jdbc:postgresql://localhost:5432/localhire
    username: localhire
    password: localhire123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # tables already created by init.sql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: localhire-super-secret-jwt-key-change-in-production-min-256-bits
  expiration: 86400000   # 24 hours in ms

logging:
  level:
    com.localhire: DEBUG
    org.springframework.security: TRACE

kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false